routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::group(['middleware' => ['web', 'can:shop']], function ()
{

    Route::get('/shop', 'ShopController@index')->name('shop.index');
    Route::get('/shop/add', 'ShopController@showAddPage')->name('shop.add.page');
    Route::post('/shop/add', 'ShopController@add')->name('shop.add');
    Route::get('/shop/delete/{id?}', 'ShopController@delete')->name('shop.delete');
    Route::get('/shop/orders', 'ShopController@orders')->name('shop.orders');

});

Route::group(['middleware' => ['web', 'can:orders']], function ()
{

    Route::get('/orders', 'UserController@index')->name('orders.index');;
    Route::get('/orders/add', 'UserController@showAddPage')->name('orders.add.page');
    Route::post('/orders/add', 'UserController@add')->name('orders.add');
    Route::get('/orders/delete/{id}', 'UserController@delete')->name('orders.delete');

});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use function app;

class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    const STATUS_REGISTERED = '1';
    const STATUS_CATCHED = '2';
    const STATUS_CONFIRMED = '3';

    protected $orderHelper;

    protected $fillable = [
        'name', 'price_min', 'price_max', 'manufacturer_id', 'status'
    ];

    public function manufacturer()
    {
        return $this->hasOne('App\Models\Manufacturer', 'id', 'manufacturer_id');
    }

    public function products()
    {
        return Product::where('name', 'LIKE', '%'.$this->name.'%')
            ->where('price', '<=', $this->price_max)
            ->where('price', '>=', $this->price_min)
            ->where('manufacturer_id', $this->manufacturer()->id)->get();
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    public function getHelper()
    {
        return $this->orderHelper;
    }

    protected function getTranslatedStatusAttribute()
    {
        $model = __CLASS__;
        return app()->make('App\Helpers\OrderHelper')
            ->translateStatus($model, $this->status);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    const CREDENTIALS_USERNAME = 'login';
    const CREDENTIALS_PASSWORD = 'password';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'login', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo('App\Models\Role');
    }

    public function products()
    {
        if($this->role->isShop()) {
            return $this->belongsToMany('App\Models\Product', 'user_product')
                ->using('App\Models\UserProduct');
        }
        else {
            return null;
        }
    }

    public function orders()
    {
        if(empty($this->products())) {
            return $this->hasMany('App\Models\Order', 'user_id', 'id');
        }
    }

    public function getSuitableOrdersAttrubute()
    {
        return $this->products()->orders;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use App\Events\OrderCreated;
use App\Models\Manufacturer;
use App\Models\Order;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function index()
    {
        $userId = Auth::id();
        /**
         * @var User $shop
         * @var Collection $products
         */
        $user = User::where('id', $userId)->first();
        $orders = $user->orders;

        return view('user.index')->with([
            'orders' => $orders
        ]);
    }

    public function showAddPage(Request $request)
    {
        $manufacturers = Manufacturer::all();
        return view('user.add', ['manufacturers' => $manufacturers]);
    }

    public function add(Request $request)
    {
        $input = $request->all();
        $orderName = $input['name'];
        $orderPriceMin = $input['price_min'];
        $orderPriceMax = $input['price_max'];
        $productManufacturerId = $input['manufacturer_id'];

        try{
            $order = User::find(Auth::id())->orders()->create([
                'name' => $orderName,
                'price_min' => $orderPriceMin,
                'price_max' => $orderPriceMax,
                'manufacturer_id' => $productManufacturerId
            ]);
        }
        catch (ModelNotFoundException $e) {
            return redirect()->back()->with([
                'error' => 'Заявка не была добавлена.'
            ]);
        }

        event(new OrderCreated($order));

        return redirect()->back()->with(['success' => 'Заявка была успешно добавлена.']);
    }

    public function delete($id)
    {
        try {
            Order::find($id)->delete();
        }
        catch (\Exception $e) {
            return redirect()->back()->with([
                'error' => 'Не удалось удалить заявку.'
            ]);
        }

        return redirect()->back()->with(['success' => 'Заявка была успешно удалена.']);
    }

}

resources/views/user/add.blade.php
@extends('layouts.app')

@section('navbar')
    @include('shared.user-navbar')
@endsection

@section('content')

    <div class="row">
        <div class="container text-center">
            <h3 class="section-header">Добавить заявку на продукцию</h3>
            <h4>Заполните поля в форме ниже</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="{{ route('orders.add')}}" method="POST">
                {{csrf_field()}}
            <div>
                <div class="form-group">
                    <label for="name">Наименование товара</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="price_min">Минимальная цена от: (в руб.)</label>
                    <input type="price" class="form-control" id="price_min" name="price_min" required>
                </div>
                <div class="form-group">
                    <label for="price_max">Максимальная цена до: (в руб.)</label>
                    <input type="price" class="form-control" id="price_max" name="price_max" required>
                </div>
                <div class="form-group">
                    <label for="manufacturer_id">Производитель</label>
                    <select class="form-control" id="manufacturer_id" name="manufacturer_id">
                        @foreach($manufacturers as $manufacturer)
                            <option value="{{$manufacturer->id}}">{{ $manufacturer->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div>
                    <button type="submit" class="btn btn-default submit">
                        <i class="fa fa-paper-plane" aria-hidden="true"></i>  Добавить заявку на продукцию
                    </button>
                </div>
            </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('navbar')
    @include('shared.user-navbar')
@endsection

@section('content')
    <div class="container">
        <div class="row col-md-10 col-md-offset-1 custyle">
            <table class="table table-striped custab">
                <thead>
                <tr>
                    <th>Наименование</th>
                    <th>Цена минимальная (в руб.)</th>
                    <th>Цена максимальная (в руб.)</th>
                    <th>Производитель</th>
                    <th>Cтатус заявки</th>
                    <th class="text-center"></th>
                </tr>
                </thead>

                @foreach($orders as $order)
                    <tr>
                        <td>{{ $order->name }}</td>
                        <td>{{ $order->price_min }}</td>
                        <td>{{ $order->price_max }}</td>
                        <td>{{ $order->manufacturer->name }}</td>
                        <td>{{ $order->translated_status }}</td>
                        <td class="text-center"><a class='btn btn-danger btn-warning' href="{{
                        route('orders.delete', $order->id)}}">Удалить</a></td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection